First try
Seems like it work.
But we need to figure out how to add System.ServiceModel.Primitives.
ERROR: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.